### ISSUE TITLE
Can't get it to start.

### ISSUE THREAD

**Issue by sebastienvg** [n1try/telegram-bot-node-sample#1]
Hi, 

I copied the code from raw save it, then added the package.json and npm installed before I tried to run it and here is the output I got.

```
seb@tx2500:~/telegramBot-nodejs$ nodejs telegram-bot.js 
Polling now.
Starting new request to https://api.telegram.org/bot/getUpdates?offset=0&timeout=60

SyntaxError: Unexpected token <
    at Object.parse (native)
    at /home/seb/telegramBot-nodejs/telegram-bot.js:50:34
    at Request.handleRequestResponse [as _callback] (/home/seb/telegramBot-nodejs/node_modules/unirest/index.js:461:25)
    at Request.self.callback (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:373:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:1318:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:1266:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

I am pretty new to nodeJS so maybe you can pin point a newbie mistake?

**Comment by n1try** [comment]
Hello,

 

without having your code I can just guess what the problem is, but actually I think it’s easy.

Did you forgot to set the BOT_TOKEN variable to your actual bot’s token? Your log says that a request to  <https://api.telegram.org/bot/getUpdates?offset=0&timeout=60> https://api.telegram.org/bot/getUpdates?offset=0&timeout=60 was made. This URL doesn’t contain any information about which specific bot to actually query messages for and therefore is redirected to the Telegram website, which obviously isn’t JSON format but HTML and especially starting with a “<” from “<html>” as first character. As a result the JSON parser fails and you get this error.

 

Regards,

Ferdinand

 

Von: Sebastien Vayrette-Gavard [mailto:notifications@github.com] 
Gesendet: Montag, 23. November 2015 21:16
An: n1try/telegram-bot-node-sample <telegram-bot-node-sample@noreply.github.com>
Betreff: [telegram-bot-node-sample] Can't get it to start. (#1)

 

Hi, 

I copied the code from raw save it, then added the package.json and npm installed before I tried to run it and here is the output I got.

seb@tx2500:~/telegramBot-nodejs$ nodejs telegram-bot.js 
Polling now.
Starting new request to https://api.telegram.org/bot/getUpdates?offset=0&timeout=60
 
SyntaxError: Unexpected token <
    at Object.parse (native)
    at /home/seb/telegramBot-nodejs/telegram-bot.js:50:34
    at Request.handleRequestResponse [as _callback] (/home/seb/telegramBot-nodejs/node_modules/unirest/index.js:461:25)
    at Request.self.callback (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:373:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:1318:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/seb/telegramBot-nodejs/node_modules/unirest/node_modules/request/request.js:1266:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16

I am pretty new to nodeJS so maybe you can pin point a newbie mistake?

**Comment by sebastienvg** [comment]
Hi, 

I wish it was that simple, I copied the code and added the token between the "" at the top of the file. the token I got has a :semi colon is it a problem?

**Comment by Swiftzn** [comment]
Ok the problem i found was that the following was missing

```javascript
// Dummy database --> in a real world application this won't be an in-memory JavaScript object, but a database connection
var questions = [
{
    q : "Birds can fly.",
    correct : true,
    answered_by : []
},
{
    q : "1 + 1 equals 3",
    correct : false,
    answered_by : []
}
];

// Array which will map a user id to the question he recently got displayed and hasn't answered yet
var active_questions = [];
```

After i added those it worked just fine
